# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e99a8f9b1bc144cdb6b3f0c2cb588dae61ca3279600400a22c733405f5e9ebf3827f3271244f361fdb2dffb2d7c97288190614d322397d8afde4e5dc45c5ebe1

test:
  secret_key_base: 336614b6efa176dbe5453d9c9eccd24eecc82ff5f7275611acab8cc04df8095239d224ded23dc36d39057ae52b2be875d7576e07c36891749b7f41900b793c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
